config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :t_weets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 't_weets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/t_weet.rb
class TWeet < ApplicationRecord
  	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :t_weets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end

	def acount_update_params
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/t_weets_controller.rb
class TWeetsController < ApplicationController
  before_action :set_t_weet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /t_weets
  # GET /t_weets.json
  def index
    @t_weets = TWeet.all.order("created_at DESC")
    @t_weet = TWeet.new
  end

  # GET /t_weets/1
  # GET /t_weets/1.json
  def show
  end

  # GET /t_weets/new
  def new
    @t_weet = current_user.t_weets.build
  end

  # GET /t_weets/1/edit
  def edit
  end

  # POST /t_weets
  # POST /t_weets.json
  def create
    @t_weet = current_user.t_weets.build(t_weet_params)

    respond_to do |format|
      if @t_weet.save
        format.html { redirect_to @t_weet, notice: 'T weet was successfully created.' }
        format.json { render :show, status: :created, location: @t_weet }
      else
        format.html { render :new }
        format.json { render json: @t_weet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /t_weets/1
  # PATCH/PUT /t_weets/1.json
  def update
    respond_to do |format|
      if @t_weet.update(t_weet_params)
        format.html { redirect_to root_path, notice: 'T weet was successfully updated.' }
        format.json { render :show, status: :ok, location: @t_weet }
      else
        format.html { render :edit }
        format.json { render json: @t_weet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /t_weets/1
  # DELETE /t_weets/1.json
  def destroy
    @t_weet.destroy
    respond_to do |format|
      format.html { redirect_to t_weets_url, notice: 'T weet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_t_weet
      @t_weet = TWeet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def t_weet_params
      params.require(:t_weet).permit(:Tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/t_weets_helper.rb
module TWeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="notification is-primary global-notification">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>

  <nav class="navbar is-info">
    <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-5">TwitterClone</h1>
    <% end %>
    <div class="navbar-burger burger" data-target="navbarExample">
        <span></span>
        <span></span>
        <span></span>
    </div>
   </div>

   <div id="navbarExample" class="navbar-menu">
   				<div class="navbar-end">
             <div class="navbar-item">
   					<div class="field is-grouped">
   						<p class="control">
   							<%= link_to 'New Tweet', root_path, class: "button is-info is-inverted" %>
   						</p>
               <% if user_signed_in? %>
                 <p class="control">
                   <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
                 </p>
                 <p>
                   <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
                 </p>
               <% else %>
               <p class="control">
                 <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
               </p>
   						<p class="control">
                 <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
               </p>
               <% end %>
               </div>
   					</div>
   				</div>
   			</div>
     	</nav>



    <%= yield %>

  </body>
</html>

app/views/t_weets/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
	<article class="media box">
		<figure class="media-left">
			<p class="image is-64x64">
				<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
			</p>
		</figure>
		<div class="media-content">
			 <%= render 't_weets/form' %>
		</div>
	</article>
  <% end %>


<% @t_weets.each do | t_weet | %>
  <div class="box">
  	<article class="media">
  		<div class="media-left">
  			<figure class="image is-64x64">
  				<%= gravatar_image_tag(t_weet.user.email, size: 64, alt: t_weet.user.name) %>
  			</figure>
  		</div>
  		<div class="media-content">
  			<div class="content">
  				<strong><%= t_weet.user.name %></strong><br />
  				<small><%= t_weet.user.username %></small><br/>
  				<p><%= t_weet.tweeet %></p>
  			</div>
        <% if user_signed_in? && current_user.id == t_weet.user_id %>
  			<nav class="level">
  				<div class="level-left is-mobile">
  					<%= link_to t_weet, class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to edit_tweeet_path(t_weet), class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to t_weet, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" } do %>
  							<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  					<% end %>
  				</div>
  			</nav>
        <% end %>
  		</div>
  	</article>
  </div>
<% end %>
</div>

app/views/t_weets/_form.html.erb
<%= simple_form_for(@t_weet) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :t_weet, label: "Tweet about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweet...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/t_weets/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweets</p>
						<p class="title is-6"><%= current_user.t_weets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">123</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">465K</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/t_weets/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			Trend 1
		</a>
		<a class="panel-block">
			Trend 2
		</a>
		<a class="panel-block">
			Trend 3
		</a>
		<a class="panel-block">
			Trend 4
		</a>
		<a class="panel-block">
			Trend 5
		</a>
		<a class="panel-block">
			Trend 6
		</a>
	</nav>
</div>

app/views/t_weets/_who-to-follow.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Who to Follow</p>

	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Mert EFE</strong>
						<small>@mertefe</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Mert Efe</strong>
						<small>@mertefe</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Mert Efe</strong>
						<small>@mertefe</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	</nav>
</div>

app/views/t_weets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweet</h1>
				<%= render 'form', t_weet: @t_weet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', t_weets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/t_weets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
    	<% if user_signed_in? %>
    		<%= render 'profile' %>
    	<% else %>
       <%= render 'trends' %>
      <% end %>

       <%= render 'feed' %>
       <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/t_weets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Tweet</h1>
					<%= render 'form', t_weet: @t_weet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', t_weets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/t_weets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @t_weet.Tweet %>
</p>

<%= link_to 'Edit', edit_t_weet_path(@t_weet) %> |
<%= link_to 'Back', t_weets_path %>